In [66]:
import numpy as np
import traceback

In [67]:
def getDimension():
    try:
        m = int(input("Enter the row size ").strip())
        n = int(input("\nEnter the column size ").strip())
    except EOFError:
        print("There is no input provided by the user, try again! ")
    return m,n

In [68]:
def printDimension(m,n):
    print("\nDimensions of the generated random matrix are {0}x{1}".format(m,n))

In [76]:
def generateRandomMatrix(m,n):
    matrix = np.random.rand(m,n)
    return matrix

In [77]:
def roundoff_dS(value, sig_digits):
    if value != 0:
        return round(value, sig_digits)
    else: 
        return 0

In [81]:
m,n=5,4
matrix = np.random.rand(m,n)
for i in range(m):
    for j in range(n):
        matrix[i][j]=roundoff_dS(matrix[i][j],4)
print(matrix)

[[0.9481 0.0016 0.8473 0.7375]
 [0.1385 0.1374 0.2475 0.5263]
 [0.3256 0.5012 0.8355 0.8073]
 [0.2518 0.7691 0.8159 0.3647]
 [0.5786 0.8258 0.7534 0.2256]]


In [71]:
def printMatrix(mat):
    print('\n'+'*'*25)
    print("\nRandom Matrix Generated\n")
    print(mat,'\n')
    print('*'*25+'\n')

In [72]:
def calculateNorm(matrix):
    pass

### Driver Code

In [75]:
try :
    row,column = getDimension()
    if row>column:
        printDimension(row,column)
        random_matrix = generateRandomMatrix(row,column)
        printMatrix(random_matrix)
        calculateNorm(random_matrix)
    else:
        print("\nRow size should be greater than the column size for the program to run\n")
        
except Exception : 
    print("\nEncountered an exception",traceback.format_exc(),"\n")

Enter the row size  5

Enter the column size  4



Dimensions of the generated random matrix are 5x4

Encountered an exception Traceback (most recent call last):
  File "<ipython-input-75-0ef848c09b9d>", line 5, in <module>
    random_matrix = generateRandomMatrix(row,column)
  File "<ipython-input-74-73c90b8ca980>", line 2, in generateRandomMatrix
    matrix = round(np.random.rand(m,n),5)
TypeError: type numpy.ndarray doesn't define __round__ method
 

