# Question 1 (ii) - Vijay Arora (2021FC04306)

In [143]:
from numpy import *
import numpy as np

# Gauss Elimination Without Pivoting

In [142]:
'''Function for handling inputs based on option provided'''
def input_selection(x):
    if (x==1):
        A = array([[1,2],
         [-1,1]],float)
        b = array([6,3],float)
        n = len(b)
        print("Input Matrix \n",A,"\n\n","b Vector : ",b,"\n\n","length : ",n,"\n")
        return A,b,n
    elif (x==2):
        A = array([[2,2,-1],
         [-1,1,2],
         [0,-1,2]],float)
        b = array([6,3,-4],float)
        n = len(b)
        print("Input Matrix \n",A,"\n\n","b Vector : ",b,"\n\n","length : ",n,"\n")
        return A,b,n
    elif(x==3):
        A = array([[2,0,3,7],
                 [0,8,2,3],
                 [1,0,5,2],
                [0,1,1,9]],float)
        b = array([4,-3,-7,10],float)
        n=len(b)
        print("Input Matrix \n",A,"\n\n","b Vector : ",b,"\n\n","length : ",n,"\n")
        return A,b,n

In [141]:
'''Function for converting operation results to significant digits specified'''
def dsig(val,sig_val):
    if val == 0:
        return 0
    return round(val,sig_val-int(math.floor(math.log10(abs(val)))) - 1)

### Forward Elimination

In [138]:
'''Function for Forward Elimination without Pivoting'''
def forward_elimination(A,b,n,digit):
        countA,countD,countM=0,0,0
        for k in range (0,n-1):             #row is k
            for i in range(k+1,n):
                if(A[k,k]!=0):
                    factor=dsig((A[i,k] / A[k,k]),digit)
                    countD+=1
                A[i][k]=0
                for j in range(k+1,n):
                    A[i,j]=dsig((A[i,j]-dsig((factor*A[k,j]),digit)),digit)
                    countA+=1
                    countM+=1
                b[i]=dsig((b[i]-dsig((factor*b[k]),digit)),digit)
                countA+=1
        operation_count = {
            'addition': countA,
            'multiplication': countA,
            'division': countD
        }       
 
        return operation_count

### Backward Substitution

In [139]:
'''Function for Backward Substitution without Pivoting'''
def backward_sub(A,b,n,digit):
    cntA,cntD,cntM=0,0,0
    x=np.zeros(n)
    x[n-1] = dsig((b[n-1]/A[n-1,n-1]),digit)
    cntD+=1
    for row in range(n-2,-1,-1):
        sum = b[row]
        for j in range(row+1,n):
            sum=dsig((sum - dsig((A[row,j] * x[j]),digit)),digit)
            cntA+=1
            cntM+=1
        x[row]=dsig((sum/A[row,row]),digit)
        cntD+=1
        operation_cnt = {
        'addition': cntA,
        'multiplication': cntM,
        'division': cntD
    }    

    return x,operation_cnt

In [140]:
'''Function for gauss without pivoting'''
def gauss_without_pivoting(A,b,digit):
    matrixA = np.matrix.copy(A)
    matrixb = np.matrix.copy(b)
    n=len(matrixb)
    forward_count = forward_elimination(matrixA,matrixb,n,digit)
    sol,backward_count=backward_sub(matrixA,matrixb,n,digit)
    out = {k: forward_count[k] + backward_count[k] for k in forward_count.keys() & backward_count.keys()}
    print("Total Operations on {0}x{0} : {1} \n".format(n,out))
    print("Solution of given system is : {0} \n".format(sol))

### Driver Code for without pivoting

In [130]:
significant_digit_input = int(input("Enter the value of significant digits \n\n"))

option = int(input('''\nEnter 1 for running program with 2x2 matrix as input.
Enter 2 for running program with 3x3 matrix as input. 
Enter 3 for running program with 4x4 matrix as input.
Note : Any other input will be considered invalid \n\n'''))

matrix_A,matrix_B,size = input_selection(option)

gauss_without_pivoting(matrix_A,matrix_B,significant_digit_input)

Enter the value of significant digits 

5

Enter 1 for running program with 2x2 matrix as input.
Enter 2 for running program with 3x3 matrix as input. 
Enter 3 for running program with 4x4 matrix as input.
Note : Any other input will be considered invalid 

3
Input Matrix 
 [[2. 0. 3. 7.]
 [0. 8. 2. 3.]
 [1. 0. 5. 2.]
 [0. 1. 1. 9.]] 

 b Vector :  [ 4. -3. -7. 10.] 

 length :  4 

Total Operations on 4x4 : {'division': 10, 'addition': 26, 'multiplication': 26} 

Solution of given system is : [ 0.15945 -0.39524 -1.982    1.3753 ] 



# Gauss Elimination With Pivoting

### Forward Elimination with pivoting

In [144]:
'''Function for Forward Elimination with Pivoting'''
def forward_elimination_with_pivoting(A,b,n,digit):
        countA,countD,countM=0,0,0
        for k in range (0,n-1):   #row is k
            temp_maxval = abs(A[k][k])
            k_temp = k
            # Check if pivoting need to be done
            for s in range(k + 1,n):
                if (abs((A[s][k])) > temp_maxval):
                    temp_maxval = abs(A[s][k])
                    k_temp = s
            #Checking for pivoting
            if k_temp != k:
                temp = np.copy(A[k])
                A[k] = A[k_temp]
                A[k_temp] = temp
                temp1 = np.copy(b[k])
                b[k] = b[k_temp]
                b[k_temp] = temp1
            
            for i in range(k+1,n):  
                factor=dsig((A[i,k] / A[k,k]),digit)
                countD+=1
                A[i][k]=0   
                for j in range(k+1,n):
                    A[i,j]=dsig((A[i,j]-dsig((factor*A[k,j]),digit)),digit)
                    countA+=1
                    countM+=1
                b[i]=dsig((b[i]-dsig((factor*b[k]),digit)),digit)
                countA+=1
        operation_count = {
            'addition': countA,
            'multiplication': countA,
            'division': countD
        }       

        return operation_count

### Backward Substitution with pivoting

In [136]:
'''Function for Backward Substitution with Pivoting'''
def backward_sub_with_pivoting(A,b,n,digit):
    cntA,cntD,cntM=0,0,0
    x=np.zeros(n)
    x[n-1] = dsig((b[n-1]/A[n-1,n-1]),digit)
    cntD+=1
    for row in range(n-2,-1,-1):
        sum = b[row]
        for j in range(row+1,n):
            sum=dsig((sum - dsig((A[row,j] * x[j]),digit)),digit)
            cntA+=1
            cntM+=1
        x[row]=dsig((sum/A[row,row]),digit)
        cntD+=1
        operation_cnt = {
        'addition': cntA,
        'multiplication': cntM,
        'division': cntD
    }    
        

    return x,operation_cnt

In [135]:
'''Function for gauss with pivoting'''
def gauss_with_pivoting(A,b,digit):
    matrixA1 = np.matrix.copy(A)
    matrixb1 = np.matrix.copy(b)
    n=len(matrixb1)
    forward_count = forward_elimination_with_pivoting(matrixA1,matrixb1,n,digit)
    sol,backward_count=backward_sub_with_pivoting(matrixA1,matrixb1,n,digit)
    out = {k: forward_count[k] + backward_count[k] for k in forward_count.keys() & backward_count.keys()}
    print("Total Operations on {0}x{0} : {1} \n".format(n,out))
    print("Solution of given system is : {0} \n".format(sol))

### Driver code for with pivoting

In [134]:
significant_digit_input1 = int(input("Enter the value of significant digits \n\n"))

option1 = int(input('''\nEnter 1 for running program with 2x2 matrix as input.
Enter 2 for running program with 3x3 matrix as input. 
Enter 3 for running program with 4x4 matrix as input.
Note : Any other input will be considered invalid \n\n'''))

matrix_A1,matrix_B1,size1 = input_selection(option1)

gauss_with_pivoting(matrix_A1,matrix_B1,significant_digit_input1)

Enter the value of significant digits 

5

Enter 1 for running program with 2x2 matrix as input.
Enter 2 for running program with 3x3 matrix as input. 
Enter 3 for running program with 4x4 matrix as input.
Note : Any other input will be considered invalid 

3
Input Matrix 
 [[2. 0. 3. 7.]
 [0. 8. 2. 3.]
 [1. 0. 5. 2.]
 [0. 1. 1. 9.]] 

 b Vector :  [ 4. -3. -7. 10.] 

 length :  4 

[[2. 0. 3. 7.]
 [0. 8. 2. 3.]
 [1. 0. 5. 2.]
 [0. 1. 1. 9.]]
[ 4. -3. -7. 10.]
[[ 2.   0.   3.   7. ]
 [ 0.   8.   2.   3. ]
 [ 0.   0.   3.5 -1.5]
 [ 0.   1.   1.   9. ]]
[ 4. -3. -9. 10.]
[[ 2.     0.     3.     7.   ]
 [ 0.     8.     2.     3.   ]
 [ 0.     0.     3.5   -1.5  ]
 [ 0.     0.     0.75   8.625]]
[ 4.    -3.    -9.    10.375]
Total Operations on 4x4 : {'division': 10, 'addition': 26, 'multiplication': 26} 

Solution of given system is : [ 0.15945 -0.39524 -1.982    1.3753 ] 

