### Importing required packages

In [58]:
import numpy as np

### Function for input selection

In [59]:
def input_selection(x):
    if (x==1):
        b = np.array([[9,2,1,1],
                 [0,8,2,3],
                 [1,0,5,2],
                [1,0,3,7]],float)
        n=len(b)
        print("input \n",b,"\n\n","length : ",n,"\n")
        return b,n
    elif (x==2):
        b = np.array([[2,1,1,9],
                 [0,8,2,3],
                 [1,0,5,2],
                [7,0,3,1]],float)
        n=len(b)
        print("input \n",b,"\n\n","length : ",n,"\n")
        return b,n
    elif(x==3):
        b = np.array([[2,1,1,9],
                 [0,8,2,3],
                 [1,0,5,2],
                [2,0,3,7]],float)
        n=len(b)
        print("input \n",b,"\n\n","length : ",n,"\n")
        return b,n

### Function to check if the matrix is Diagonally Dominant

In [60]:
def isDDM(b,n):
    flag = True
    for i in range (n):
        x,sumD=0,0
        for j in range(n):
            if(i!=j):
                sumD+=abs(b[i][j])
        print("\n Sum without diagonal element for row {0} : {1}".format(i+1,sumD)) 
        x=b[i][i]
        print("\n Diagonal element for row {0}: {1}".format(i+1,abs(x)))
        if (abs(x)>abs(sumD)):
            flag = True
        else:
            flag = False
            return flag
    return flag

### Function to check if the matrix can be made Diagonally Dominant

In [61]:
def canbeDDM(b,n):
    a=np.zeros((n,n),float)
    for i in range(n):
        x,sumD=0,0
        for j in range(n):
            sumD+=abs(b[i][j])  
            
        for k in range(n):
            sumD-=abs(b[i][k])
            if(abs(b[i][k])>sumD):
                a[i][k]=1
                sumD+=abs(b[i][k])
            else:
                a[i][k]=0
                sumD+=abs(b[i][k])
    
    print("\n Resultant Vector \n",a)
    for i in range (n):
        col_sum=0
        for j in range(n):
            col_sum+=a[j][i]
        
        if(col_sum!=1):
            return "\n ------------ \n Matrix cannot be made diagonally dominant as column sum for column {} is {}".format(i+1,col_sum)
        
    return "\n ------------ \n Matrix can be made diagonally dominant"

### Driver Code

In [62]:
size = int(input("You can only enter size as 4 for this question but I used this so that it can be made variable in future \n\n"))

matrix = np.zeros((size,size),float)

option = int(input('''\nEnter 1 for running program with diagonally dominant matrix as input.
Enter 2 for running program with diagonally non-dominant matrix which can be converted into DDM as input. 
Enter 3 for running program with diagonally non-dominant matrix which cannot be converted into DDM as input.
Note : Any other input will be considered invalid \n\n'''))

input_matrix,size = input_selection(option)

ddm_flag = isDDM(input_matrix,size)
if(ddm_flag==False):
    if_ddm = canbeDDM(input_matrix,size)
    print(if_ddm)
else:
    print("\n --------------- \n Matrix is diagonally dominant ")

You can only enter size as 4 for this question but I used this so that it can be made variable in future 

4

Enter 1 for running program with diagonally dominant matrix as input.
Enter 2 for running program with diagonally non-dominant matrix which can be converted into DDM as input. 
Enter 3 for running program with diagonally non-dominant matrix which cannot be converted into DDM as input.
Note : Any other input will be considered invalid 

3
input 
 [[2. 1. 1. 9.]
 [0. 8. 2. 3.]
 [1. 0. 5. 2.]
 [2. 0. 3. 7.]] 

 length :  4 


 Sum without diagonal element for row 1 : 11.0

 Diagonal element for row 1: 2.0

 Resultant Vector 
 [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 ------------ 
 Matrix cannot be made diagonally dominant as column sum for column 1 is 0.0
