# Gauss Elimination Without Pivoting

In [36]:
from numpy import *

In [15]:
# A = array([[1,2,-1,2],
#          [-1,1,2,1],
#          [2,-1,2,4],
#         [4,-6,8,7]],float)
# b = array([6,3,14,5])
# n = len(b)
# x = zeros(n,float)
# print("A : {0} \n b : {1} \n x : {2}".format(A,b,x))

A : [[ 1.  2. -1.  2.]
 [-1.  1.  2.  1.]
 [ 2. -1.  2.  4.]
 [ 4. -6.  8.  7.]] 
 b : [ 6  3 14  5] 
 x : [0. 0. 0. 0.]


In [37]:
A = array([[1,2,-1],
         [-1,1,2],
         [2,-1,2]],float)
b = array([6,3,-4])
n = len(b)
x = zeros(n,float)
print("A : {0} \n b : {1} \n x : {2}".format(A,b,x))

A : [[ 1.  2. -1.]
 [-1.  1.  2.]
 [ 2. -1.  2.]] 
 b : [ 6  3 -4] 
 x : [0. 0. 0.]


### Forward Elimination

In [38]:
countD,countM,countS,countA=0,0,0,0
for k in range (0,n-1):             #row is k
    for i in range(k+1,n):
        factor=A[i,k] / A[k,k]
        countD+=1
        for j in range(k,n):
            A[i,j]=A[i,j]-factor*A[k,j]
            countM+=1
            if (factor * A[i][k] > 0):
                countS+=1
            else:
                countA+=1
        b[i]=b[i]-factor*b[k]
        countM+=1
        if (factor * A[i][k] > 0):
            countS+=1
        else:
            countA+=1
print("A = \n{0} \n and \n b = \n{1}".format(A,b))
print("\n Count for : \n Division {0} \n Multiplication {1} \n Addition {2} \n Subtraction {3}".format(countD,countM,countA,countS))

A = 
[[ 1.          2.         -1.        ]
 [ 0.          3.          1.        ]
 [ 0.          0.          5.66666667]] 
 and 
 b = 
[ 6  9 -1]

 Count for A : 
 Division 3 
 Multiplication 11 
 Addition 11 
 Subtraction 0


### Backward Substitution

In [44]:
cntD,cntM,cntA,cntS=0,0,0,0
x[n-1] = b[n-1]/A[n-1,n-1]
cntD+=1
for row in range(n-2,-1,-1):
    sum = b[row]
    for j in range(row+1,n):
        sum-=A[row,j] * x[j]
        cntM+=1
        if (A[row,j] * x[j] > 0):
            cntS+=1
        else:
            cntA+=1
    x[row]=sum/A[row,row]
    cntD+=1
    
print("\n Count for : \n Division {0} \n Count for Multiplication {1} \n Count for Addition {2} \n Count for Subtraction {3} \n Solution of system (x) : {4}".format(cntD,cntM,cntA,cntS,x))
print("")



 Count for : 
 Division 3 
 Count for Multiplication 3 
 Count for Addition 1 
 Count for Subtraction 2 
 Solution of system (x) : [-0.29411765  3.05882353 -0.17647059]



In [45]:
print("Total count for Division : {}".format(cntD+countD))
print("Total count for Multiplication : {}".format(cntM+countM))
print("Total count for Addition or Subtraction : {}".format(cntA+countA+cntS+countS))

Total count for Division : 6
Total count for Multiplication : 14
Total count for Addition or Subtraction : 14


In [46]:
linalg.solve(A,b)

array([-0.29411765,  3.05882353, -0.17647059])