In [11]:
import numpy as np
from numpy import *
from random import *

In [14]:
def isDDM(b,n):
    flag = True
    for i in range (n):
        x,sumD=0,0
        for j in range(n):
            if(i!=j):
                sumD+=abs(b[i][j])
        x=b[i][i]
        if (abs(x)>abs(sumD)):
            flag = True
        else:
            flag = False
            return flag
    return flag

In [3]:
def calculate_iteration_matrix(b,n):
    for i in range(n):
        x=b[i][i]
        for j in range(n):
            b[i][j]=b[i][j]/x
            
    L = np.zeros(shape=(n,n),dtype=float)
    U = np.zeros(shape=(n,n),dtype=float)
    I = np.identity(n,dtype=float)
    for i in range(n):
        for j in range(n):
            if j<i:
                L[i][j]=b[i][j]
            if j>i:
                U[i][j]=b[i][j]
                
    I_L = np.add(L,I)
    I_L_Inverse = np.linalg.inv(I_L)
    I_L_Inverse_U = np.dot(I_L_Inverse,U)
    I_L_Inverse_U = I_L_Inverse_U*-1
    print ("L :\n",L,"\n")
    print ("U:\n",U,"\n")
    print ("I:\n",I,"\n")
    print("Iteration matrix:\n",I_L_Inverse_U,"\n")
    return I_L_Inverse_U

In [4]:
def calculate_norm(I_L_Inverse_U):
    print("supermum norm \t\t",np.linalg.norm(I_L_Inverse_U,np.inf))
    print("l2 norm \t\t",np.linalg.norm(I_L_Inverse_U,'fro'))
    print("l1 norm \t\t",np.linalg.norm(I_L_Inverse_U,1))

In [7]:
def generateRandomMatrix(N):
    matrix = np.float_(np.random.randint(1,50, size=(N, N)))
    for i in range(matrix.shape[0]):
        row  = matrix[i].copy()
        row_sum = sum(row)
        if random()>0.65:
            matrix[i,i] = row_sum+np.random.randint(5)
#     input_matrix = np.zeros(shape=(N,N), dtype=float)
#     augmented_matrix_list = list()
#     for row in range(0,N):
#         for col in range (0,N):
#             input_matrix[row][col] = np.random.randint(0,9)
#     b_vector = np.zeros(N)
#     for i in range(N):
#         b_vector[i]  = np.random.randint(0,9)
#     print("input A : \n {0} \n b_vector : \n {1} \n".format(matrix,b_vector))
    print("input A : \n {0}\n".format(matrix))
    return matrix

In [6]:
n = 4
flag = False
m_flag = False
I_L_Inverse_U = np.zeros(shape=(n,n),dtype=float)
# matrix = np.zeros(shape=(n,n),dtype=float)

In [4]:
# #DDM
# a = np.array([[9,2,1,1],
#          [0,8,2,3],
#          [1,0,5,2],
#         [1,0,3,7]],float)
# b = np.copy(a)
# print("input \n",b,"\n")

input 
 [[9. 2. 1. 1.]
 [0. 8. 2. 3.]
 [1. 0. 5. 2.]
 [1. 0. 3. 7.]] 



In [15]:
# matrix,m_flag = random_matrix(n)
mat = generateRandomMatrix(n)
flag = isDDM(mat,n)
print (flag,"\n")
if(flag):
    I_L_Inverse_U = calculate_iteration_matrix(mat,n)
    calculate_norm(I_L_Inverse_U)
else:
    print("Need to run again as all the random matrices were non diagonal dominant")

input A : 
 [[ 13.  26.  39.  49.]
 [ 12.  18.  35.  27.]
 [ 22.  25.  37.   1.]
 [ 40.  27.  45. 115.]]

False 

Need to run again as all the random matrices were non diagonal dominant


In [22]:
mat = generateRandomMatrix(n)
I_L_Inverse_U = calculate_iteration_matrix(mat,n)
calculate_norm(I_L_Inverse_U)

input A : 
 [[ 83.  32.  11.  24.]
 [ 19.  19.  15.  20.]
 [ 36.  24. 141.  48.]
 [ 23.  26.  35.  98.]]

L :
 [[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 [0.25531915 0.17021277 0.         0.        ]
 [0.23469388 0.26530612 0.35714286 0.        ]] 

U:
 [[0.         0.38554217 0.13253012 0.28915663]
 [0.         0.         0.78947368 1.05263158]
 [0.         0.         0.         0.34042553]
 [0.         0.         0.         0.        ]] 

I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

Iteration matrix:
 [[-0.         -0.38554217 -0.13253012 -0.28915663]
 [-0.          0.38554217 -0.65694356 -0.76347495]
 [-0.          0.0328121   0.14565766 -0.13664512]
 [-0.         -0.02352092  0.15337457  0.3192197 ]] 

supermum norm 		 1.8059606848446417
l2 norm 		 1.2569300095242912
l1 norm 		 1.5084964030539967
