In [7]:
import numpy as np
from numpy import linalg
from math import *
from random import *

In [203]:
def isDDM(b,n):
    flag = True
    for i in range (n):
        x,sumD=0,0
        for j in range(n):
            if(i!=j):
                sumD+=abs(b[i][j])
        print("\n Sum with diagonal element for {0} : {1}".format(i,sumD)) 
        x=b[i][i]
        print("\n diagonal element for {0}: {1}".format(i,abs(x)))
        if (abs(x)>abs(sumD)):
            flag = True
        else:
            flag = False
            return flag
    return flag

In [202]:
def canbeDDM(b,n):
    for i in range(n):
        x,sumD=0,0
        for j in range(n):
            sumD+=abs(b[i][j])  
            
        for k in range(n):
            sumD-=abs(b[i][k])
            if(abs(b[i][k])>sumD):
                a[i][k]=1
            else:
                a[i][k]=0
    for i in range (n):
        for j in range(n):
            sum+=a[j][i]
        
        if(sum!=1):
            return "Cannot be made diagonally dominant"
        
    return "Can be made diagonally dominant"

In [2]:
def calculate_iteration_matrix(b,n):
    for i in range(n):
        x=b[i][i]
        for j in range(n):
            b[i][j]=b[i][j]/x
            
    L = np.zeros(shape=(n,n),dtype=float)
    U = np.zeros(shape=(n,n),dtype=float)
    for i in range(n):
        for j in range(n):
            if j<i:
                L[i][j]=b[i][j]
            if j>i:
                U[i][j]=b[i][j]
                
    L_U = np.add(L,U)
    L_U = L_U*-1
    print ("L :\t",L,"\n")
    print ("U:\t",U,"\n")
    print("Iteration matrix:\n",L_U,"\n")
    return L_U

In [3]:
def calculate_norm(L_U):
    print("supermum norm \t\t",np.linalg.norm(L_U,np.inf))
    print("l2 norm \t\t",np.linalg.norm(L_U,'fro'))
    print("l1 norm \t\t",np.linalg.norm(L_U,1))

In [ ]:
# a = np.array([[9,2,9,7],
#          [3,8,4,6],
#          [5,8,8,5],
#         [2,6,7,9]],float)
# b = np.copy(a)

In [ ]:
# a = np.array([[5,-1,3],
#          [2,-8,1],
#          [-2,0,4]],float)
# b = np.copy(a)

In [ ]:
# a = np.array([[4,2,-2],
#          [0,4,2],
#          [1,0,4]],float)
# b = np.copy(a)

In [ ]:
# #DDM
# a = np.array([[4,2,1],
#          [0,4,2],
#          [1,0,4]],float)
# b = np.copy(a)

In [207]:
#DDM
a = np.array([[9,2,1,1],
         [0,8,2,3],
         [1,0,5,2],
        [1,0,3,7]],float)
b = np.copy(a)
print("input \n",b,"\n")

input 
 [[9. 2. 1. 1.]
 [0. 8. 2. 3.]
 [1. 0. 5. 2.]
 [1. 0. 3. 7.]] 



In [ ]:
# a = np.array([[1,-5],
#          [7,-1]],float)
# b = np.copy(a)

In [208]:
n = 4
flag = False
m_flag = False
L_U = np.zeros(shape=(n,n),dtype=float)
# matrix = np.zeros(shape=(n,n),dtype=float)

In [161]:
a = np.random.randint(-10,10,(n,n))
a = np.array(a,dtype=float)
b = np.copy(a)

In [209]:
# matrix,m_flag = random_matrix(n)
print("input :\t",b,"\n")
flag = isDDM(b,n)
print (flag,"\n")
if(flag):
    L_U = calculate_iteration_matrix(b,n)
    calculate_norm(L_U)
else:
    print("Need to run again as all the random matrices were non diagonal dominant")

input :	 [[9. 2. 1. 1.]
 [0. 8. 2. 3.]
 [1. 0. 5. 2.]
 [1. 0. 3. 7.]] 


 Sum with diagonal element for 0 : 4.0

 diagonal element for 0: 9.0

 Sum with diagonal element for 1 : 5.0

 diagonal element for 1: 8.0

 Sum with diagonal element for 2 : 3.0

 diagonal element for 2: 5.0

 Sum with diagonal element for 3 : 4.0

 diagonal element for 3: 7.0
True 

L :	 [[0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.2        0.         0.         0.        ]
 [0.14285714 0.         0.42857143 0.        ]] 

U:	 [[0.         0.22222222 0.11111111 0.11111111]
 [0.         0.         0.25       0.375     ]
 [0.         0.         0.         0.4       ]
 [0.         0.         0.         0.        ]] 

Iteration matrix:
 [[-0.         -0.22222222 -0.11111111 -0.11111111]
 [-0.         -0.         -0.25       -0.375     ]
 [-0.2        -0.         -0.         -0.4       ]
 [-0.14285714 -0.         -0.42857143 -0.        ]] 

supermum norm 		 0.625
l

In [5]:
def generateRandomMatrix(N):
    matrix = np.float_(np.random.randint(1,50, size=(N, N)))
    for i in range(matrix.shape[0]):
        row  = matrix[i].copy()
        row_sum = sum(row)
        if random()>0.65:
            matrix[i,i] = row_sum+np.random.randint(5)
#     input_matrix = np.zeros(shape=(N,N), dtype=float)
#     augmented_matrix_list = list()
#     for row in range(0,N):
#         for col in range (0,N):
#             input_matrix[row][col] = np.random.randint(0,9)
#     b_vector = np.zeros(N)
#     for i in range(N):
#         b_vector[i]  = np.random.randint(0,9)
#     print("input A : \n {0} \n b_vector : \n {1} \n".format(matrix,b_vector))
    print("input A : \n {0}\n".format(matrix))
    return matrix

In [18]:
n=4
LU = np.zeros(shape=(n,n),dtype=float)
mat = generateRandomMatrix(n)
LU = calculate_iteration_matrix(mat,n)
calculate_norm(LU)

input A : 
 [[ 44.  20.  39.  21.]
 [ 29. 129.  32.  45.]
 [ 15.   5.  38.   7.]
 [ 33.  48.  44. 133.]]

L :	 [[0.         0.         0.         0.        ]
 [0.2248062  0.         0.         0.        ]
 [0.39473684 0.13157895 0.         0.        ]
 [0.2481203  0.36090226 0.33082707 0.        ]] 

U:	 [[0.         0.45454545 0.88636364 0.47727273]
 [0.         0.         0.24806202 0.34883721]
 [0.         0.         0.         0.18421053]
 [0.         0.         0.         0.        ]] 

Iteration matrix:
 [[-0.         -0.45454545 -0.88636364 -0.47727273]
 [-0.2248062  -0.         -0.24806202 -0.34883721]
 [-0.39473684 -0.13157895 -0.         -0.18421053]
 [-0.2481203  -0.36090226 -0.33082707 -0.        ]] 

supermum norm 		 1.8181818181818181
l2 norm 		 1.4007589710880939
l1 norm 		 1.4652527195366851


In [ ]:
def guass_operation_count(n: int):
    """
    n: Number of row / columns in a square matrix
    """
    # Operation count for addition
    ref_addition = int((n * (n+1) * (2 * n + 1)) / 6) # Number of addition for REF
    backsub_addition = int((n * (n - 1)) / 2)
    total_addition = ref_addition + backsub_addition
    
    # Operation count for multiplication
    total_multiplication = total_addition # Same as addition
    
    # Operation count for division
    ref_division = int((n * (n-1)) / 2)
    backsub_division = n
    total_division = ref_division + backsub_division

    # Summarize
    operation_count = {
        'addition': total_addition,
        'multiplication': total_multiplication,
        'division': total_division
    }
    
    return operation_count

In [4]:
for i in range(100,1100,100):
    efficiency = {'test_case': [i], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 
              'theoritical_time': []}
    print(efficiency)

{'test_case': [100], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 'theoritical_time': []}
{'test_case': [200], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 'theoritical_time': []}
{'test_case': [300], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 'theoritical_time': []}
{'test_case': [400], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 'theoritical_time': []}
{'test_case': [500], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 'theoritical_time': []}
{'test_case': [600], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 'theoritical_time': []}
{'test_case': [700], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 'theoritical_time': []}
{'test_case': [800], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 'theoritical_time': []}
{'test_case': [900], 'with_pivoting_time_taken': [], 'without_pivoting_time_taken': [], 'theoritical_tim